# Generated by Django 3.1.3 on 2022-12-10 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MilestoneApp', '0004_auto_20221210_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_image',
        ),
    ]
